-- STAGING-ONLY structural bootstrap from the schema-v4 catalog observed 2026-09-25.
-- Applies no Supabase rows and does not assert full schema, operation, or security parity.
-- Keep frontend and Worker feature selectors disabled until each operation gate is implemented.
-- Deferred: auth.users foreign keys, now() defaults, functions, RLS, triggers, views,
-- locale-sensitive checks, row-import validation, GIN indexes, and the fanmark_events sequence state.
-- Generated by scripts/migration/schema-convert.mjs.

-- This is structural preparation only; inspect the adjacent gates report before applying.

-- Source catalog: 40 tables, 406 columns, 144 constraints, 139 indexes.

-- Deployable claim: false.

-- D1 SQL execution rejects explicit BEGIN/COMMIT; apply only through a reviewed migration runner.

PRAGMA foreign_keys = ON;

CREATE TABLE "audit_logs" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT,
  "action" TEXT NOT NULL,
  "resource_type" TEXT NOT NULL,
  "resource_id" TEXT,
  "request_id" TEXT,
  "metadata" TEXT DEFAULT '{}',
  "created_at" TEXT NOT NULL,
  CONSTRAINT "d1_audit_logs_metadata_7" CHECK ("metadata" IS NULL OR json_valid("metadata")),
  CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "broadcast_emails" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "subject" TEXT NOT NULL,
  "body_text" TEXT NOT NULL,
  "email_type" TEXT NOT NULL DEFAULT 'broadcast_announcement',
  "recipient_filter" TEXT DEFAULT '{}',
  "total_recipients" INTEGER DEFAULT 0,
  "sent_count" INTEGER DEFAULT 0,
  "failed_count" INTEGER DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "created_by" TEXT,
  "scheduled_at" TEXT,
  "started_at" TEXT,
  "completed_at" TEXT,
  "error_details" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_broadcast_emails_recipient_filter_5" CHECK ("recipient_filter" IS NULL OR json_valid("recipient_filter")),
  CONSTRAINT "d1_broadcast_emails_total_recipients_7" CHECK ("total_recipients" IS NULL OR (typeof("total_recipients") = 'integer' AND "total_recipients" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_broadcast_emails_sent_count_9" CHECK ("sent_count" IS NULL OR (typeof("sent_count") = 'integer' AND "sent_count" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_broadcast_emails_failed_count_11" CHECK ("failed_count" IS NULL OR (typeof("failed_count") = 'integer' AND "failed_count" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_broadcast_emails_error_details_18" CHECK ("error_details" IS NULL OR json_valid("error_details")),
  CONSTRAINT "broadcast_emails_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "broadcast_emails_status_check" CHECK (status IN ('draft', 'scheduled', 'sending', 'completed', 'failed', 'cancelled'))
);

CREATE TABLE "email_templates" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "email_type" TEXT NOT NULL,
  "language" TEXT NOT NULL DEFAULT 'ja',
  "subject" TEXT NOT NULL,
  "body_text" TEXT NOT NULL,
  "button_text" TEXT NOT NULL,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_email_templates_is_active_7" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "email_templates_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "email_templates_email_type_language_key" UNIQUE ("email_type", "language")
);

CREATE TABLE "emoji_master" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "emoji" TEXT NOT NULL,
  "short_name" TEXT NOT NULL,
  "keywords" TEXT NOT NULL DEFAULT '[]',
  "category" TEXT,
  "subcategory" TEXT,
  "codepoints" TEXT NOT NULL,
  "sort_order" INTEGER,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_emoji_master_keywords_4" CHECK ("keywords" IS NULL OR (json_valid("keywords") AND json_type("keywords") = 'array')),
  CONSTRAINT "d1_emoji_master_codepoints_8" CHECK ("codepoints" IS NULL OR (json_valid("codepoints") AND json_type("codepoints") = 'array')),
  CONSTRAINT "d1_emoji_master_sort_order_10" CHECK ("sort_order" IS NULL OR (typeof("sort_order") = 'integer' AND "sort_order" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "emoji_master_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "emoji_master_emoji_key" UNIQUE ("emoji")
);

CREATE TABLE "enterprise_user_settings" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT NOT NULL,
  "custom_fanmarks_limit" INTEGER,
  "custom_pricing" INTEGER,
  "notes" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "created_by" TEXT,
  CONSTRAINT "d1_enterprise_user_settings_custom_fanmarks_limit_3" CHECK ("custom_fanmarks_limit" IS NULL OR (typeof("custom_fanmarks_limit") = 'integer' AND "custom_fanmarks_limit" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_enterprise_user_settings_custom_pricing_5" CHECK ("custom_pricing" IS NULL OR (typeof("custom_pricing") = 'integer' AND "custom_pricing" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "enterprise_user_settings_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "enterprise_user_settings_user_id_key" UNIQUE ("user_id")
);

CREATE TABLE "extension_coupon_usages" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "coupon_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "fanmark_id" TEXT NOT NULL,
  "license_id" TEXT NOT NULL,
  "used_at" TEXT NOT NULL,
  CONSTRAINT "extension_coupon_usages_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "extension_coupon_usages_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "extension_coupons" ("id") ON DELETE CASCADE,
  CONSTRAINT "extension_coupon_usages_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id"),
  CONSTRAINT "extension_coupon_usages_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id")
);

CREATE TABLE "extension_coupons" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "code" TEXT NOT NULL,
  "months" INTEGER NOT NULL,
  "allowed_tier_levels" TEXT,
  "max_uses" INTEGER NOT NULL DEFAULT 1,
  "used_count" INTEGER NOT NULL DEFAULT 0,
  "expires_at" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_extension_coupons_months_3" CHECK (typeof("months") = 'integer' AND "months" BETWEEN -32768 AND 32767),
  CONSTRAINT "d1_extension_coupons_allowed_tier_levels_5" CHECK ("allowed_tier_levels" IS NULL OR (json_valid("allowed_tier_levels") AND json_type("allowed_tier_levels") = 'array')),
  CONSTRAINT "d1_extension_coupons_max_uses_7" CHECK (typeof("max_uses") = 'integer' AND "max_uses" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_extension_coupons_used_count_9" CHECK (typeof("used_count") = 'integer' AND "used_count" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_extension_coupons_is_active_12" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "extension_coupons_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "extension_coupons_code_key" UNIQUE ("code"),
  CONSTRAINT "extension_coupons_months_check" CHECK (months IN (1, 2, 3, 6))
);

CREATE TABLE "fanmark_access_daily_stats" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "fanmark_id" TEXT NOT NULL,
  "license_id" TEXT,
  "stat_date" TEXT NOT NULL,
  "access_count" INTEGER DEFAULT 0,
  "unique_visitors" INTEGER DEFAULT 0,
  "referrer_direct" INTEGER DEFAULT 0,
  "referrer_search" INTEGER DEFAULT 0,
  "referrer_social" INTEGER DEFAULT 0,
  "referrer_other" INTEGER DEFAULT 0,
  "device_mobile" INTEGER DEFAULT 0,
  "device_tablet" INTEGER DEFAULT 0,
  "device_desktop" INTEGER DEFAULT 0,
  "created_at" TEXT,
  "updated_at" TEXT,
  "access_type_profile" INTEGER DEFAULT 0,
  "access_type_redirect" INTEGER DEFAULT 0,
  "access_type_text" INTEGER DEFAULT 0,
  "access_type_inactive" INTEGER DEFAULT 0,
  CONSTRAINT "d1_fanmark_access_daily_stats_access_count_5" CHECK ("access_count" IS NULL OR (typeof("access_count") = 'integer' AND "access_count" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_unique_visitors_7" CHECK ("unique_visitors" IS NULL OR (typeof("unique_visitors") = 'integer' AND "unique_visitors" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_referrer_direct_9" CHECK ("referrer_direct" IS NULL OR (typeof("referrer_direct") = 'integer' AND "referrer_direct" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_referrer_search_11" CHECK ("referrer_search" IS NULL OR (typeof("referrer_search") = 'integer' AND "referrer_search" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_referrer_social_13" CHECK ("referrer_social" IS NULL OR (typeof("referrer_social") = 'integer' AND "referrer_social" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_referrer_other_15" CHECK ("referrer_other" IS NULL OR (typeof("referrer_other") = 'integer' AND "referrer_other" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_device_mobile_17" CHECK ("device_mobile" IS NULL OR (typeof("device_mobile") = 'integer' AND "device_mobile" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_device_tablet_19" CHECK ("device_tablet" IS NULL OR (typeof("device_tablet") = 'integer' AND "device_tablet" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_device_desktop_21" CHECK ("device_desktop" IS NULL OR (typeof("device_desktop") = 'integer' AND "device_desktop" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_access_type_profile_25" CHECK ("access_type_profile" IS NULL OR (typeof("access_type_profile") = 'integer' AND "access_type_profile" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_access_type_redirect_27" CHECK ("access_type_redirect" IS NULL OR (typeof("access_type_redirect") = 'integer' AND "access_type_redirect" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_access_type_text_29" CHECK ("access_type_text" IS NULL OR (typeof("access_type_text") = 'integer' AND "access_type_text" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_access_daily_stats_access_type_inactive_31" CHECK ("access_type_inactive" IS NULL OR (typeof("access_type_inactive") = 'integer' AND "access_type_inactive" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "fanmark_access_daily_stats_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_access_daily_stats_fanmark_id_stat_date_key" UNIQUE ("fanmark_id", "stat_date"),
  CONSTRAINT "fanmark_access_daily_stats_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_access_daily_stats_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE SET NULL
);

CREATE TABLE "fanmark_access_logs" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "fanmark_id" TEXT NOT NULL,
  "license_id" TEXT,
  "accessed_at" TEXT NOT NULL,
  "referrer" TEXT,
  "referrer_domain" TEXT,
  "referrer_category" TEXT,
  "user_agent" TEXT,
  "device_type" TEXT,
  "browser" TEXT,
  "os" TEXT,
  "utm_source" TEXT,
  "utm_medium" TEXT,
  "utm_campaign" TEXT,
  "visitor_hash" TEXT,
  "access_type" TEXT,
  CONSTRAINT "fanmark_access_logs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_access_logs_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_access_logs_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE SET NULL
);

CREATE TABLE "fanmark_availability_rules" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "rule_type" TEXT NOT NULL,
  "priority" INTEGER NOT NULL,
  "rule_config" TEXT NOT NULL DEFAULT '{}',
  "is_available" INTEGER NOT NULL DEFAULT 1,
  "price_usd" INTEGER,
  "description" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "created_by" TEXT,
  CONSTRAINT "d1_fanmark_availability_rules_priority_3" CHECK (typeof("priority") = 'integer' AND "priority" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_fanmark_availability_rules_rule_config_5" CHECK ("rule_config" IS NULL OR json_valid("rule_config")),
  CONSTRAINT "d1_fanmark_availability_rules_is_available_7" CHECK (typeof("is_available") = 'integer' AND "is_available" IN (0, 1)),
  CONSTRAINT "d1_fanmark_availability_rules_price_usd_9" CHECK ("price_usd" IS NULL OR (typeof("price_usd") = 'integer' AND "price_usd" BETWEEN -9999999999 AND 9999999999)),
  CONSTRAINT "fanmark_availability_rules_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_availability_rules_priority_check" CHECK (priority >= 1 AND priority <= 4),
  CONSTRAINT "fanmark_availability_rules_rule_type_check" CHECK (rule_type IN ('specific_pattern', 'duplicate_pattern', 'prefix_pattern', 'count_based'))
);

CREATE TABLE "fanmark_basic_configs" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "license_id" TEXT NOT NULL,
  "fanmark_name" TEXT,
  "access_type" TEXT NOT NULL DEFAULT 'inactive',
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "fanmark_basic_configs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_basic_configs_license_id_key" UNIQUE ("license_id"),
  CONSTRAINT "fanmark_basic_configs_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE
);

CREATE TABLE "fanmark_discoveries" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "emoji_ids" TEXT NOT NULL,
  "normalized_emoji_ids" TEXT NOT NULL,
  "fanmark_id" TEXT,
  "availability_status" TEXT NOT NULL DEFAULT 'unknown',
  "first_seen_at" TEXT NOT NULL,
  "last_seen_at" TEXT NOT NULL,
  "search_count" INTEGER NOT NULL DEFAULT 0,
  "favorite_count" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "d1_fanmark_discoveries_emoji_ids_2" CHECK ("emoji_ids" IS NULL OR (json_valid("emoji_ids") AND json_type("emoji_ids") = 'array')),
  CONSTRAINT "d1_fanmark_discoveries_normalized_emoji_ids_4" CHECK ("normalized_emoji_ids" IS NULL OR (json_valid("normalized_emoji_ids") AND json_type("normalized_emoji_ids") = 'array')),
  CONSTRAINT "d1_fanmark_discoveries_search_count_10" CHECK (typeof("search_count") = 'integer' AND "search_count" BETWEEN -9223372036854775808 AND 9223372036854775807),
  CONSTRAINT "d1_fanmark_discoveries_favorite_count_12" CHECK (typeof("favorite_count") = 'integer' AND "favorite_count" BETWEEN -9223372036854775808 AND 9223372036854775807),
  CONSTRAINT "fanmark_discoveries_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_discoveries_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE SET NULL,
  CONSTRAINT "fanmark_discoveries_availability_check" CHECK (availability_status IN ('unknown', 'unclaimed', 'claimed_external', 'owned_by_user'))
);

CREATE TABLE "fanmark_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "event_type" TEXT NOT NULL,
  "user_id" TEXT,
  "discovery_id" TEXT,
  "normalized_emoji_ids" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  CONSTRAINT "d1_fanmark_events_id_1" CHECK (typeof("id") = 'integer' AND "id" BETWEEN -9223372036854775808 AND 9223372036854775807),
  CONSTRAINT "d1_fanmark_events_normalized_emoji_ids_6" CHECK ("normalized_emoji_ids" IS NULL OR (json_valid("normalized_emoji_ids") AND json_type("normalized_emoji_ids") = 'array')),
  CONSTRAINT "fanmark_events_discovery_id_fkey" FOREIGN KEY ("discovery_id") REFERENCES "fanmark_discoveries" ("id") ON DELETE SET NULL
);

CREATE TABLE "fanmark_favorites" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT NOT NULL,
  "discovery_id" TEXT NOT NULL,
  "fanmark_id" TEXT,
  "normalized_emoji_ids" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "display_fanmark" TEXT,
  CONSTRAINT "d1_fanmark_favorites_normalized_emoji_ids_5" CHECK ("normalized_emoji_ids" IS NULL OR (json_valid("normalized_emoji_ids") AND json_type("normalized_emoji_ids") = 'array')),
  CONSTRAINT "fanmark_favorites_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_favorites_discovery_id_fkey" FOREIGN KEY ("discovery_id") REFERENCES "fanmark_discoveries" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_favorites_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE SET NULL
);

CREATE TABLE "fanmark_licenses" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "fanmark_id" TEXT NOT NULL,
  "user_id" TEXT,
  "license_start" TEXT NOT NULL,
  "license_end" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "is_initial_license" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "plan_excluded" INTEGER DEFAULT 0,
  "excluded_at" TEXT,
  "excluded_from_plan" TEXT,
  "grace_expires_at" TEXT,
  "is_returned" INTEGER NOT NULL DEFAULT 0,
  "is_transferred" INTEGER NOT NULL DEFAULT 0,
  "transfer_locked_until" TEXT,
  "display_fanmark" TEXT,
  CONSTRAINT "d1_fanmark_licenses_is_initial_license_7" CHECK (typeof("is_initial_license") = 'integer' AND "is_initial_license" IN (0, 1)),
  CONSTRAINT "d1_fanmark_licenses_plan_excluded_11" CHECK ("plan_excluded" IS NULL OR (typeof("plan_excluded") = 'integer' AND "plan_excluded" IN (0, 1))),
  CONSTRAINT "d1_fanmark_licenses_is_returned_16" CHECK (typeof("is_returned") = 'integer' AND "is_returned" IN (0, 1)),
  CONSTRAINT "d1_fanmark_licenses_is_transferred_18" CHECK (typeof("is_transferred") = 'integer' AND "is_transferred" IN (0, 1)),
  CONSTRAINT "fanmark_licenses_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fk_fanmark_licenses_fanmark_id" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_licenses_status_check" CHECK (status IN ('active', 'grace', 'expired'))
);

CREATE TABLE "fanmark_lottery_entries" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "fanmark_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "license_id" TEXT NOT NULL,
  "lottery_probability" TEXT NOT NULL DEFAULT '1.0',
  "entry_status" TEXT NOT NULL DEFAULT 'pending',
  "applied_at" TEXT NOT NULL,
  "lottery_executed_at" TEXT,
  "won_at" TEXT,
  "cancelled_at" TEXT,
  "cancellation_reason" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "fanmark_lottery_entries_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "unique_fanmark_user_license" UNIQUE ("fanmark_id", "user_id", "license_id"),
  CONSTRAINT "fanmark_lottery_entries_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_lottery_entries_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE,
  CONSTRAINT "positive_probability" CHECK (typeof("lottery_probability") = 'text' AND length("lottery_probability") > 0 AND instr("lottery_probability", char(0)) = 0 AND "lottery_probability" NOT GLOB '*[^0-9.]*' AND "lottery_probability" NOT GLOB '*.*.*' AND substr("lottery_probability", 1, 1) GLOB '[0-9]' AND (substr("lottery_probability", 1, 1) <> '0' OR substr("lottery_probability", 2, 1) = '.') AND (instr("lottery_probability", '.') = 0 OR instr("lottery_probability", '.') < length("lottery_probability")) AND replace(replace("lottery_probability", '.', ''), '0', '') <> ''),
  CONSTRAINT "valid_cancellation_reason" CHECK (cancellation_reason IS NULL OR (cancellation_reason IN ('user_request', 'license_extended', 'system'))),
  CONSTRAINT "valid_entry_status" CHECK (entry_status IN ('pending', 'won', 'lost', 'cancelled', 'cancelled_by_extension'))
);

CREATE TABLE "fanmark_lottery_history" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "fanmark_id" TEXT NOT NULL,
  "license_id" TEXT NOT NULL,
  "total_entries" INTEGER NOT NULL,
  "winner_user_id" TEXT,
  "winner_entry_id" TEXT,
  "probability_distribution" TEXT NOT NULL DEFAULT '[]',
  "random_seed" TEXT,
  "executed_at" TEXT NOT NULL,
  "execution_method" TEXT NOT NULL DEFAULT 'automatic',
  "created_at" TEXT NOT NULL,
  CONSTRAINT "d1_fanmark_lottery_history_total_entries_4" CHECK (typeof("total_entries") = 'integer' AND "total_entries" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_fanmark_lottery_history_probability_distribution_8" CHECK ("probability_distribution" IS NULL OR json_valid("probability_distribution")),
  CONSTRAINT "fanmark_lottery_history_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_lottery_history_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_lottery_history_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_lottery_history_winner_entry_id_fkey" FOREIGN KEY ("winner_entry_id") REFERENCES "fanmark_lottery_entries" ("id"),
  CONSTRAINT "valid_execution_method" CHECK (execution_method IN ('automatic', 'manual'))
);

CREATE TABLE "fanmark_messageboard_configs" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "license_id" TEXT NOT NULL,
  "content" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "fanmark_messageboard_configs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_messageboard_configs_license_id_key" UNIQUE ("license_id"),
  CONSTRAINT "fanmark_messageboard_configs_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE
);

CREATE TABLE "fanmark_password_configs" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "license_id" TEXT NOT NULL,
  "access_password" TEXT NOT NULL,
  "is_enabled" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_fanmark_password_configs_is_enabled_4" CHECK (typeof("is_enabled") = 'integer' AND "is_enabled" IN (0, 1)),
  CONSTRAINT "fanmark_password_configs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_password_configs_license_id_key" UNIQUE ("license_id"),
  CONSTRAINT "fanmark_password_configs_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE
);

CREATE TABLE "fanmark_profiles" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "license_id" TEXT NOT NULL,
  "display_name" TEXT,
  "bio" TEXT,
  "social_links" TEXT DEFAULT '{}',
  "theme_settings" TEXT DEFAULT '{}',
  "is_public" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_fanmark_profiles_social_links_5" CHECK ("social_links" IS NULL OR json_valid("social_links")),
  CONSTRAINT "d1_fanmark_profiles_theme_settings_7" CHECK ("theme_settings" IS NULL OR json_valid("theme_settings")),
  CONSTRAINT "d1_fanmark_profiles_is_public_9" CHECK (typeof("is_public") = 'integer' AND "is_public" IN (0, 1)),
  CONSTRAINT "fanmark_profiles_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_profiles_license_id_key" UNIQUE ("license_id"),
  CONSTRAINT "fanmark_profiles_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE
);

CREATE TABLE "fanmark_redirect_configs" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "license_id" TEXT NOT NULL,
  "target_url" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "fanmark_redirect_configs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_redirect_configs_license_id_key" UNIQUE ("license_id"),
  CONSTRAINT "fanmark_redirect_configs_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE
);

CREATE TABLE "fanmark_tier_extension_prices" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "tier_level" INTEGER NOT NULL,
  "months" INTEGER NOT NULL,
  "price_yen" INTEGER NOT NULL,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "stripe_price_id" TEXT,
  "stripe_price_id_live" TEXT,
  CONSTRAINT "d1_fanmark_tier_extension_prices_tier_level_2" CHECK (typeof("tier_level") = 'integer' AND "tier_level" BETWEEN -32768 AND 32767),
  CONSTRAINT "d1_fanmark_tier_extension_prices_months_4" CHECK (typeof("months") = 'integer' AND "months" BETWEEN -32768 AND 32767),
  CONSTRAINT "d1_fanmark_tier_extension_prices_price_yen_6" CHECK (typeof("price_yen") = 'integer' AND "price_yen" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_fanmark_tier_extension_prices_is_active_8" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "fanmark_tier_extension_prices_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_tier_extension_prices_unique" UNIQUE ("tier_level", "months"),
  CONSTRAINT "fanmark_tier_extension_prices_months_check" CHECK (months >= 1),
  CONSTRAINT "fanmark_tier_extension_prices_price_check" CHECK (price_yen >= 0),
  CONSTRAINT "fanmark_tier_extension_prices_tier_check" CHECK (tier_level >= 1)
);

CREATE TABLE "fanmark_tiers" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "tier_level" INTEGER NOT NULL,
  "emoji_count_min" INTEGER NOT NULL,
  "emoji_count_max" INTEGER NOT NULL,
  "monthly_price_usd" INTEGER NOT NULL DEFAULT 0,
  "initial_license_days" INTEGER,
  "description" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  CONSTRAINT "d1_fanmark_tiers_tier_level_2" CHECK (typeof("tier_level") = 'integer' AND "tier_level" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_fanmark_tiers_emoji_count_min_4" CHECK (typeof("emoji_count_min") = 'integer' AND "emoji_count_min" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_fanmark_tiers_emoji_count_max_6" CHECK (typeof("emoji_count_max") = 'integer' AND "emoji_count_max" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_fanmark_tiers_monthly_price_usd_8" CHECK (typeof("monthly_price_usd") = 'integer' AND "monthly_price_usd" BETWEEN -9999999999 AND 9999999999),
  CONSTRAINT "d1_fanmark_tiers_initial_license_days_10" CHECK ("initial_license_days" IS NULL OR (typeof("initial_license_days") = 'integer' AND "initial_license_days" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_fanmark_tiers_is_active_13" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "fanmark_tiers_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_tiers_tier_level_key" UNIQUE ("tier_level")
);

CREATE TABLE "fanmark_transfer_codes" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "license_id" TEXT NOT NULL,
  "fanmark_id" TEXT NOT NULL,
  "issuer_user_id" TEXT NOT NULL,
  "transfer_code" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "expires_at" TEXT NOT NULL,
  "disclaimer_agreed_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "fanmark_transfer_codes_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_transfer_codes_transfer_code_key" UNIQUE ("transfer_code"),
  CONSTRAINT "fanmark_transfer_codes_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_transfer_codes_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE,
  CONSTRAINT "valid_transfer_code_status" CHECK (status IN ('active', 'applied', 'completed', 'cancelled', 'expired'))
);

CREATE TABLE "fanmark_transfer_requests" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "transfer_code_id" TEXT NOT NULL,
  "license_id" TEXT NOT NULL,
  "fanmark_id" TEXT NOT NULL,
  "requester_user_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "disclaimer_agreed_at" TEXT NOT NULL,
  "applied_at" TEXT NOT NULL,
  "resolved_at" TEXT,
  "rejection_reason" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "requester_username" TEXT,
  "requester_display_name" TEXT,
  CONSTRAINT "fanmark_transfer_requests_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmark_transfer_requests_fanmark_id_fkey" FOREIGN KEY ("fanmark_id") REFERENCES "fanmarks" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_transfer_requests_license_id_fkey" FOREIGN KEY ("license_id") REFERENCES "fanmark_licenses" ("id") ON DELETE CASCADE,
  CONSTRAINT "fanmark_transfer_requests_transfer_code_id_fkey" FOREIGN KEY ("transfer_code_id") REFERENCES "fanmark_transfer_codes" ("id") ON DELETE CASCADE,
  CONSTRAINT "valid_transfer_request_status" CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'expired'))
);

CREATE TABLE "fanmarks" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_input_fanmark" TEXT NOT NULL,
  "normalized_emoji" TEXT NOT NULL,
  "short_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "emoji_ids" TEXT NOT NULL DEFAULT '[]',
  "normalized_emoji_ids" TEXT NOT NULL DEFAULT '[]',
  "tier_level" INTEGER NOT NULL,
  CONSTRAINT "d1_fanmarks_emoji_ids_8" CHECK ("emoji_ids" IS NULL OR (json_valid("emoji_ids") AND json_type("emoji_ids") = 'array')),
  CONSTRAINT "d1_fanmarks_normalized_emoji_ids_10" CHECK ("normalized_emoji_ids" IS NULL OR (json_valid("normalized_emoji_ids") AND json_type("normalized_emoji_ids") = 'array')),
  CONSTRAINT "d1_fanmarks_tier_level_12" CHECK (typeof("tier_level") = 'integer' AND "tier_level" BETWEEN -32768 AND 32767),
  CONSTRAINT "fanmarks_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fanmarks_normalized_emoji_ids_unique" UNIQUE ("normalized_emoji_ids"),
  CONSTRAINT "fanmarks_short_id_key" UNIQUE ("short_id"),
  CONSTRAINT "fanmarks_user_input_fanmark_unique" UNIQUE ("normalized_emoji"),
  CONSTRAINT "fanmarks_short_id_length" CHECK (length(short_id) >= 6),
  CONSTRAINT "fanmarks_status_check" CHECK (status IN ('active', 'inactive')),
  CONSTRAINT "fanmarks_status_valid" CHECK (status IN ('active', 'reserved', 'banned')),
  CONSTRAINT "fanmarks_tier_level_check" CHECK (tier_level >= 1)
);

CREATE TABLE "invitation_codes" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "code" TEXT NOT NULL,
  "max_uses" INTEGER NOT NULL DEFAULT 1,
  "used_count" INTEGER NOT NULL DEFAULT 0,
  "expires_at" TEXT,
  "special_perks" TEXT DEFAULT '{}',
  "created_by" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_invitation_codes_max_uses_3" CHECK (typeof("max_uses") = 'integer' AND "max_uses" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_invitation_codes_used_count_5" CHECK (typeof("used_count") = 'integer' AND "used_count" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_invitation_codes_special_perks_8" CHECK ("special_perks" IS NULL OR json_valid("special_perks")),
  CONSTRAINT "d1_invitation_codes_is_active_11" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "invitation_codes_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "invitation_codes_code_key" UNIQUE ("code"),
  CONSTRAINT "invitation_codes_max_uses_positive" CHECK (max_uses > 0),
  CONSTRAINT "invitation_codes_used_count_valid" CHECK (used_count >= 0 AND used_count <= max_uses)
);

CREATE TABLE "languages" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "code" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "native_label" TEXT NOT NULL,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_languages_is_active_5" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "d1_languages_sort_order_7" CHECK (typeof("sort_order") = 'integer' AND "sort_order" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "languages_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "languages_code_key" UNIQUE ("code")
);

CREATE TABLE "notification_events" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "event_type" TEXT NOT NULL,
  "event_version" INTEGER NOT NULL DEFAULT 1,
  "source" TEXT NOT NULL,
  "payload" TEXT NOT NULL DEFAULT '{}',
  "payload_schema" TEXT,
  "trigger_at" TEXT NOT NULL,
  "dedupe_key" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "processed_at" TEXT,
  "error_reason" TEXT,
  "retry_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_notification_events_event_version_3" CHECK (typeof("event_version") = 'integer' AND "event_version" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notification_events_payload_6" CHECK ("payload" IS NULL OR json_valid("payload")),
  CONSTRAINT "d1_notification_events_retry_count_14" CHECK (typeof("retry_count") = 'integer' AND "retry_count" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "notification_events_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "unique_event_dedupe" UNIQUE ("event_type", "dedupe_key"),
  CONSTRAINT "notification_events_source_check" CHECK (source IN ('system', 'cron_job', 'edge_function', 'admin_ui', 'admin_manual', 'batch')),
  CONSTRAINT "notification_events_status_check" CHECK (status IN ('pending', 'processing', 'processed', 'failed', 'skipped'))
);

CREATE TABLE "notification_preferences" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "event_type" TEXT,
  "enabled" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_notification_preferences_enabled_5" CHECK (typeof("enabled") = 'integer' AND "enabled" IN (0, 1)),
  CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "unique_user_channel_event" UNIQUE ("user_id", "channel", "event_type"),
  CONSTRAINT "notification_preferences_channel_check" CHECK (channel IN ('in_app', 'email', 'webpush'))
);

CREATE TABLE "notification_rules" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "event_type" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "template_id" TEXT NOT NULL,
  "template_version" INTEGER NOT NULL DEFAULT 1,
  "delay_seconds" INTEGER NOT NULL DEFAULT 0,
  "priority" INTEGER NOT NULL DEFAULT 5,
  "segment_filter" TEXT,
  "cooldown_window_seconds" INTEGER,
  "max_per_user" INTEGER,
  "cancel_condition" TEXT,
  "enabled" INTEGER NOT NULL DEFAULT 1,
  "valid_from" TEXT,
  "valid_until" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "created_by" TEXT,
  CONSTRAINT "d1_notification_rules_template_version_5" CHECK (typeof("template_version") = 'integer' AND "template_version" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notification_rules_delay_seconds_7" CHECK (typeof("delay_seconds") = 'integer' AND "delay_seconds" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notification_rules_priority_9" CHECK (typeof("priority") = 'integer' AND "priority" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notification_rules_segment_filter_11" CHECK ("segment_filter" IS NULL OR json_valid("segment_filter")),
  CONSTRAINT "d1_notification_rules_cooldown_window_seconds_13" CHECK ("cooldown_window_seconds" IS NULL OR (typeof("cooldown_window_seconds") = 'integer' AND "cooldown_window_seconds" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_notification_rules_max_per_user_15" CHECK ("max_per_user" IS NULL OR (typeof("max_per_user") = 'integer' AND "max_per_user" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_notification_rules_enabled_18" CHECK (typeof("enabled") = 'integer' AND "enabled" IN (0, 1)),
  CONSTRAINT "notification_rules_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "notification_rules_channel_check" CHECK (channel IN ('in_app', 'email', 'webpush')),
  CONSTRAINT "notification_rules_priority_check" CHECK (priority >= 1 AND priority <= 10)
);

CREATE TABLE "notification_templates" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "template_id" TEXT NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "channel" TEXT NOT NULL,
  "language" TEXT NOT NULL DEFAULT 'ja',
  "title" TEXT,
  "body" TEXT NOT NULL,
  "summary" TEXT,
  "payload_schema" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_notification_templates_version_3" CHECK (typeof("version") = 'integer' AND "version" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notification_templates_payload_schema_10" CHECK ("payload_schema" IS NULL OR json_valid("payload_schema")),
  CONSTRAINT "d1_notification_templates_is_active_12" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "notification_templates_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "unique_template_version" UNIQUE ("template_id", "version", "channel", "language"),
  CONSTRAINT "notification_templates_channel_check" CHECK (channel IN ('in_app', 'email', 'webpush'))
);

CREATE TABLE "notifications" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "event_id" TEXT,
  "rule_id" TEXT,
  "user_id" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "template_id" TEXT NOT NULL,
  "template_version" INTEGER NOT NULL DEFAULT 1,
  "payload" TEXT NOT NULL DEFAULT '{}',
  "status" TEXT NOT NULL DEFAULT 'pending',
  "priority" INTEGER NOT NULL DEFAULT 5,
  "triggered_at" TEXT NOT NULL,
  "expires_at" TEXT,
  "delivered_at" TEXT,
  "error_reason" TEXT,
  "retry_count" INTEGER NOT NULL DEFAULT 0,
  "read_at" TEXT,
  "read_via" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_notifications_template_version_7" CHECK (typeof("template_version") = 'integer' AND "template_version" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notifications_payload_9" CHECK ("payload" IS NULL OR json_valid("payload")),
  CONSTRAINT "d1_notifications_priority_12" CHECK (typeof("priority") = 'integer' AND "priority" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_notifications_retry_count_18" CHECK (typeof("retry_count") = 'integer' AND "retry_count" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "notifications_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "notification_events" ("id") ON DELETE SET NULL,
  CONSTRAINT "notifications_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "notification_rules" ("id") ON DELETE SET NULL,
  CONSTRAINT "notifications_channel_check" CHECK (channel IN ('in_app', 'email', 'webpush')),
  CONSTRAINT "notifications_priority_check" CHECK (priority >= 1 AND priority <= 10),
  CONSTRAINT "notifications_status_check" CHECK (status IN ('pending', 'delivered', 'failed', 'cancelled', 'sending', 'sent'))
);

CREATE TABLE "notifications_history" (
  "id" TEXT NOT NULL,
  "original_data" TEXT NOT NULL,
  "archived_at" TEXT NOT NULL,
  CONSTRAINT "d1_notifications_history_original_data_2" CHECK ("original_data" IS NULL OR json_valid("original_data")),
  CONSTRAINT "notifications_history_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "reserved_emoji_patterns" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "pattern" TEXT NOT NULL,
  "price_yen" INTEGER NOT NULL,
  "description" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_reserved_emoji_patterns_price_yen_3" CHECK (typeof("price_yen") = 'integer' AND "price_yen" BETWEEN -2147483648 AND 2147483647),
  CONSTRAINT "d1_reserved_emoji_patterns_is_active_6" CHECK (typeof("is_active") = 'integer' AND "is_active" IN (0, 1)),
  CONSTRAINT "reserved_emoji_patterns_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "reserved_emoji_patterns_pattern_key" UNIQUE ("pattern")
);

CREATE TABLE "system_settings" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "setting_key" TEXT NOT NULL,
  "setting_value" TEXT NOT NULL,
  "description" TEXT,
  "is_public" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  CONSTRAINT "d1_system_settings_is_public_5" CHECK (typeof("is_public") = 'integer' AND "is_public" IN (0, 1)),
  CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "system_settings_setting_key_key" UNIQUE ("setting_key")
);

CREATE TABLE "user_roles" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "created_by" TEXT,
  CONSTRAINT "d1_user_roles_role_3" CHECK ("role" IN ('admin', 'moderator', 'user')),
  CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "user_roles_user_id_role_key" UNIQUE ("user_id", "role")
);

CREATE TABLE "user_settings" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "display_name" TEXT,
  "avatar_url" TEXT,
  "plan_type" TEXT NOT NULL DEFAULT 'free',
  "preferred_language" TEXT NOT NULL DEFAULT 'ja',
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "invited_by_code" TEXT,
  "requires_password_setup" INTEGER NOT NULL DEFAULT 0,
  "stripe_customer_id" TEXT,
  CONSTRAINT "d1_user_settings_plan_type_6" CHECK ("plan_type" IN ('free', 'creator', 'max', 'business', 'enterprise', 'admin')),
  CONSTRAINT "d1_user_settings_preferred_language_8" CHECK ("preferred_language" IN ('en', 'ja', 'ko', 'id')),
  CONSTRAINT "d1_user_settings_requires_password_setup_13" CHECK (typeof("requires_password_setup") = 'integer' AND "requires_password_setup" IN (0, 1)),
  CONSTRAINT "user_settings_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "user_settings_user_id_key" UNIQUE ("user_id"),
  CONSTRAINT "user_settings_username_key" UNIQUE ("username"),
  CONSTRAINT "user_settings_invited_by_code_fkey" FOREIGN KEY ("invited_by_code") REFERENCES "invitation_codes" ("code")
);

CREATE TABLE "user_subscriptions" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "user_id" TEXT NOT NULL,
  "stripe_customer_id" TEXT NOT NULL,
  "stripe_subscription_id" TEXT NOT NULL,
  "product_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "current_period_start" TEXT,
  "current_period_end" TEXT,
  "cancel_at_period_end" INTEGER DEFAULT 0,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "price_id" TEXT,
  "amount" INTEGER,
  "currency" TEXT,
  "interval" TEXT,
  "interval_count" INTEGER,
  "payment_failure_at" TEXT,
  "next_payment_attempt" TEXT,
  "payment_failure_type" TEXT,
  CONSTRAINT "d1_user_subscriptions_cancel_at_period_end_9" CHECK ("cancel_at_period_end" IS NULL OR (typeof("cancel_at_period_end") = 'integer' AND "cancel_at_period_end" IN (0, 1))),
  CONSTRAINT "d1_user_subscriptions_amount_14" CHECK ("amount" IS NULL OR (typeof("amount") = 'integer' AND "amount" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "d1_user_subscriptions_interval_count_18" CHECK ("interval_count" IS NULL OR (typeof("interval_count") = 'integer' AND "interval_count" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "user_subscriptions_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "user_subscriptions_user_id_stripe_subscription_id_key" UNIQUE ("user_id", "stripe_subscription_id")
);

CREATE TABLE "waitlist" (
  "id" TEXT NOT NULL DEFAULT (lower(
  hex(randomblob(4)) || '-' ||
  hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2, 3) || '-' ||
  substr('89ab', (random() & 3) + 1, 1) || substr(hex(randomblob(2)), 2, 3) || '-' ||
  hex(randomblob(6))
)),
  "email" TEXT NOT NULL,
  "referral_source" TEXT,
  "status" TEXT NOT NULL DEFAULT 'waiting',
  "created_at" TEXT NOT NULL,
  CONSTRAINT "waitlist_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "waitlist_email_key" UNIQUE ("email"),
  CONSTRAINT "waitlist_status_valid" CHECK (status IN ('waiting', 'invited', 'converted'))
);

CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" ("created_at");

CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("user_id");

CREATE INDEX "idx_broadcast_emails_created_at" ON "broadcast_emails" ("created_at" DESC);

CREATE INDEX "idx_broadcast_emails_status" ON "broadcast_emails" ("status");

CREATE INDEX "idx_emoji_master_category" ON "emoji_master" ("category", "subcategory");

CREATE INDEX "idx_extension_coupon_usages_coupon_id" ON "extension_coupon_usages" ("coupon_id");

CREATE INDEX "idx_extension_coupon_usages_user_id" ON "extension_coupon_usages" ("user_id");

CREATE INDEX "idx_extension_coupons_active" ON "extension_coupons" ("is_active") WHERE (is_active = true);

CREATE INDEX "idx_extension_coupons_code" ON "extension_coupons" ("code");

CREATE INDEX "idx_daily_stats_fanmark_date" ON "fanmark_access_daily_stats" ("fanmark_id", "stat_date");

CREATE INDEX "idx_daily_stats_fanmark_date_type" ON "fanmark_access_daily_stats" ("fanmark_id", "stat_date", "access_type_profile", "access_type_redirect", "access_type_text", "access_type_inactive");

CREATE INDEX "idx_access_logs_access_type" ON "fanmark_access_logs" ("access_type");

CREATE INDEX "idx_access_logs_accessed_at" ON "fanmark_access_logs" ("accessed_at");

CREATE INDEX "idx_access_logs_fanmark_date" ON "fanmark_access_logs" ("fanmark_id", "accessed_at");

CREATE INDEX "idx_access_logs_fanmark_id" ON "fanmark_access_logs" ("fanmark_id");

CREATE INDEX "idx_access_logs_visitor_hash" ON "fanmark_access_logs" ("visitor_hash", "accessed_at");

CREATE INDEX "idx_fanmark_availability_rules_available" ON "fanmark_availability_rules" ("is_available") WHERE (is_available = true);

CREATE INDEX "idx_fanmark_availability_rules_type_priority" ON "fanmark_availability_rules" ("rule_type", "priority");

CREATE INDEX "fanmark_discoveries_fanmark_idx" ON "fanmark_discoveries" ("fanmark_id");

CREATE INDEX "fanmark_discoveries_last_seen_idx" ON "fanmark_discoveries" ("last_seen_at" DESC);

CREATE UNIQUE INDEX "fanmark_discoveries_seq_key_idx" ON "fanmark_discoveries" ("normalized_emoji_ids");

CREATE INDEX "fanmark_events_type_created_idx" ON "fanmark_events" ("event_type", "created_at" DESC);

CREATE INDEX "fanmark_favorites_fanmark_idx" ON "fanmark_favorites" ("fanmark_id");

CREATE INDEX "fanmark_favorites_user_idx" ON "fanmark_favorites" ("user_id");

CREATE UNIQUE INDEX "fanmark_favorites_user_seq_idx" ON "fanmark_favorites" ("user_id", "normalized_emoji_ids");

CREATE INDEX "idx_fanmark_licenses_fanmark_grace" ON "fanmark_licenses" ("fanmark_id", "status", "grace_expires_at") WHERE (status IN ('active', 'grace'));

CREATE INDEX "idx_fanmark_licenses_fanmark_id" ON "fanmark_licenses" ("fanmark_id");

CREATE INDEX "idx_fanmark_licenses_grace_expires" ON "fanmark_licenses" ("grace_expires_at") WHERE (status = 'grace');

CREATE INDEX "idx_fanmark_licenses_license_end" ON "fanmark_licenses" ("license_end");

CREATE INDEX "idx_fanmark_licenses_status" ON "fanmark_licenses" ("status");

CREATE INDEX "idx_fanmark_licenses_user_id" ON "fanmark_licenses" ("user_id");

CREATE INDEX "idx_lottery_entries_fanmark_status" ON "fanmark_lottery_entries" ("fanmark_id", "entry_status");

CREATE INDEX "idx_lottery_entries_license_status" ON "fanmark_lottery_entries" ("license_id", "entry_status");

CREATE INDEX "idx_lottery_entries_user_status" ON "fanmark_lottery_entries" ("user_id", "entry_status");

CREATE INDEX "idx_lottery_history_executed_at" ON "fanmark_lottery_history" ("executed_at" DESC);

CREATE INDEX "idx_lottery_history_fanmark" ON "fanmark_lottery_history" ("fanmark_id");

CREATE INDEX "idx_transfer_codes_fanmark_id" ON "fanmark_transfer_codes" ("fanmark_id");

CREATE INDEX "idx_transfer_codes_issuer_user_id" ON "fanmark_transfer_codes" ("issuer_user_id");

CREATE INDEX "idx_transfer_codes_license_id" ON "fanmark_transfer_codes" ("license_id");

CREATE INDEX "idx_transfer_codes_status" ON "fanmark_transfer_codes" ("status");

CREATE INDEX "idx_transfer_codes_transfer_code" ON "fanmark_transfer_codes" ("transfer_code");

CREATE INDEX "idx_transfer_requests_fanmark_id" ON "fanmark_transfer_requests" ("fanmark_id");

CREATE INDEX "idx_transfer_requests_license_id" ON "fanmark_transfer_requests" ("license_id");

CREATE INDEX "idx_transfer_requests_requester_user_id" ON "fanmark_transfer_requests" ("requester_user_id");

CREATE INDEX "idx_transfer_requests_status" ON "fanmark_transfer_requests" ("status");

CREATE INDEX "idx_transfer_requests_transfer_code_id" ON "fanmark_transfer_requests" ("transfer_code_id");

CREATE UNIQUE INDEX "fanmarks_seq_key_idx" ON "fanmarks" ("normalized_emoji_ids");

CREATE INDEX "idx_fanmarks_normalized_emoji" ON "fanmarks" ("normalized_emoji");

CREATE INDEX "idx_fanmarks_status" ON "fanmarks" ("status");

CREATE INDEX "idx_invitation_codes_active" ON "invitation_codes" ("is_active", "expires_at");

CREATE INDEX "idx_invitation_codes_code" ON "invitation_codes" ("code");

CREATE INDEX "idx_languages_active" ON "languages" ("is_active", "sort_order");

CREATE INDEX "idx_notification_events_event_type" ON "notification_events" ("event_type");

CREATE INDEX "idx_notification_events_status_trigger" ON "notification_events" ("status", "trigger_at") WHERE (status = 'pending');

CREATE INDEX "idx_notification_rules_event_type" ON "notification_rules" ("event_type") WHERE (enabled = true);

CREATE INDEX "idx_notifications_status_channel" ON "notifications" ("status", "channel") WHERE (status IN ('pending', 'failed'));

CREATE INDEX "idx_notifications_user_created" ON "notifications" ("user_id", "created_at" DESC);

CREATE INDEX "idx_notifications_user_unread" ON "notifications" ("user_id", "read_at") WHERE ((read_at IS NULL) AND (channel = 'in_app'));

CREATE INDEX "idx_reserved_emoji_patterns_pattern" ON "reserved_emoji_patterns" ("pattern");

CREATE INDEX "idx_system_settings_key" ON "system_settings" ("setting_key");

CREATE INDEX "idx_user_settings_invited_by_code" ON "user_settings" ("invited_by_code") WHERE (invited_by_code IS NOT NULL);

CREATE UNIQUE INDEX "user_settings_stripe_customer_id_key" ON "user_settings" ("stripe_customer_id") WHERE (stripe_customer_id IS NOT NULL);

CREATE INDEX "idx_user_subscriptions_status" ON "user_subscriptions" ("status");

CREATE INDEX "idx_user_subscriptions_stripe_customer_id" ON "user_subscriptions" ("stripe_customer_id");

CREATE INDEX "idx_user_subscriptions_user_id" ON "user_subscriptions" ("user_id");

CREATE INDEX "idx_waitlist_email" ON "waitlist" ("email");
