-- STAGING ONLY: plan-bound business D1 runtime extension.
-- Generated by scripts/migration/business-schema-extensions.mjs.
-- DDL applies no Supabase or user rows; the final migration seeds one target runtime policy row.
-- Source fingerprint: 8435ff17c81ce4990da073b506465ea868a1e470af288fcc98c75621dae1b984
-- Extension digest: 9a83e838b916f881fe52feb9ea68009c26a0029836b37545e36675468605bae5

ALTER TABLE "fanmark_licenses" ADD COLUMN "lifecycle_generation" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("lifecycle_generation") = 'integer' AND "lifecycle_generation" BETWEEN 0 AND 9007199254740991);
ALTER TABLE "fanmark_licenses" ADD COLUMN "lifecycle_claim_id" TEXT;
CREATE TABLE "fanmark_license_incarnations" (
  "license_id" TEXT PRIMARY KEY NOT NULL,
  "incarnation" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("incarnation") = 'integer' AND "incarnation" BETWEEN 0 AND 9007199254740991)
);
CREATE TABLE "fanmark_access_versions" (
  "license_id" TEXT PRIMARY KEY NOT NULL REFERENCES "fanmark_licenses"("id"),
  "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
  "password_generation" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("password_generation") = 'integer' AND "password_generation" BETWEEN 0 AND 9007199254740991),
  "access_generation" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("access_generation") = 'integer' AND "access_generation" BETWEEN 0 AND 9007199254740991),
  "updated_at" TEXT NOT NULL
);
CREATE TABLE "license_expiry_runs" (
  "run_id" TEXT PRIMARY KEY NOT NULL,
  "target_incarnation" TEXT NOT NULL,
  "schema_extension_digest" TEXT NOT NULL,
  "captured_now" TEXT NOT NULL,
  "grace_period_days" INTEGER NOT NULL CHECK (typeof("grace_period_days") = 'integer' AND "grace_period_days" BETWEEN 1 AND 9007199254740991),
  "status" TEXT NOT NULL CHECK ("status" IN ('running', 'completed')),
  "last_license_id" TEXT NOT NULL DEFAULT '',
  "candidate_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("candidate_count") = 'integer' AND "candidate_count" BETWEEN 0 AND 9007199254740991),
  "processed_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("processed_count") = 'integer' AND "processed_count" BETWEEN 0 AND 9007199254740991),
  "conflict_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("conflict_count") = 'integer' AND "conflict_count" BETWEEN 0 AND 9007199254740991),
  "completed_at" TEXT
);
CREATE TABLE "license_expiry_run_items" (
  "run_id" TEXT NOT NULL REFERENCES "license_expiry_runs"("run_id"),
  "license_id" TEXT NOT NULL REFERENCES "fanmark_licenses"("id"),
  "fanmark_id" TEXT NOT NULL REFERENCES "fanmarks"("id"),
  "fanmark_short_id" TEXT NOT NULL,
  "fanmark_name" TEXT NOT NULL,
  "user_id" TEXT,
  "license_end" TEXT NOT NULL,
  "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
  "license_lifecycle_generation" INTEGER NOT NULL CHECK (typeof("license_lifecycle_generation") = 'integer' AND "license_lifecycle_generation" BETWEEN 0 AND 9007199254740991),
  "access_generation" INTEGER NOT NULL CHECK (typeof("access_generation") = 'integer' AND "access_generation" BETWEEN 0 AND 9007199254740991),
  "operation_id" TEXT NOT NULL,
  "audit_id" TEXT NOT NULL,
  "notification_event_id" TEXT NOT NULL,
  "outcome" TEXT NOT NULL DEFAULT 'pending' CHECK ("outcome" IN ('pending', 'processed', 'conflict')),
  "grace_expires_at" TEXT NOT NULL,
  "completed_at" TEXT,
  PRIMARY KEY ("run_id", "license_id"),
  UNIQUE ("run_id", "operation_id"),
  UNIQUE ("run_id", "audit_id"),
  UNIQUE ("run_id", "notification_event_id")
);
CREATE TABLE "license_expiry_effect_guards" (
  "operation_id" TEXT PRIMARY KEY NOT NULL,
  "allowed" INTEGER NOT NULL CHECK (typeof("allowed") = 'integer' AND "allowed" = 1)
);
CREATE TABLE "license_grace_finalization_runs" (
  "run_id" TEXT PRIMARY KEY NOT NULL,
  "target_incarnation" TEXT NOT NULL,
  "schema_extension_digest" TEXT NOT NULL,
  "captured_now" TEXT NOT NULL,
  "status" TEXT NOT NULL CHECK ("status" IN ('running', 'completed')),
  "last_license_id" TEXT NOT NULL DEFAULT '',
  "candidate_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("candidate_count") = 'integer' AND "candidate_count" BETWEEN 0 AND 9007199254740991),
  "processed_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("processed_count") = 'integer' AND "processed_count" BETWEEN 0 AND 9007199254740991),
  "conflict_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("conflict_count") = 'integer' AND "conflict_count" BETWEEN 0 AND 9007199254740991),
  "completed_at" TEXT
);
CREATE TABLE "license_grace_finalization_items" (
  "run_id" TEXT NOT NULL REFERENCES "license_grace_finalization_runs"("run_id"),
  "license_id" TEXT NOT NULL REFERENCES "fanmark_licenses"("id"),
  "fanmark_id" TEXT NOT NULL REFERENCES "fanmarks"("id"),
  "fanmark_short_id" TEXT NOT NULL,
  "fanmark_name" TEXT NOT NULL,
  "user_id" TEXT,
  "license_end" TEXT,
  "grace_expires_at" TEXT NOT NULL,
  "is_returned" INTEGER NOT NULL CHECK (typeof("is_returned") = 'integer' AND "is_returned" IN (0, 1)),
  "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
  "license_lifecycle_generation" INTEGER NOT NULL CHECK (typeof("license_lifecycle_generation") = 'integer' AND "license_lifecycle_generation" BETWEEN 0 AND 9007199254740991),
  "access_generation" INTEGER NOT NULL CHECK (typeof("access_generation") = 'integer' AND "access_generation" BETWEEN 0 AND 9007199254740991),
  "operation_id" TEXT NOT NULL,
  "audit_id" TEXT NOT NULL,
  "notification_event_id" TEXT NOT NULL,
  "outcome" TEXT NOT NULL DEFAULT 'pending' CHECK ("outcome" IN ('pending', 'processed', 'conflict')),
  "completed_at" TEXT,
  PRIMARY KEY ("run_id", "license_id"),
  UNIQUE ("run_id", "operation_id"),
  UNIQUE ("run_id", "audit_id"),
  UNIQUE ("run_id", "notification_event_id")
);
CREATE INDEX "fanmark_licenses_lifecycle_scan" ON "fanmark_licenses" ("status", "license_end", "lifecycle_generation");
CREATE INDEX "fanmark_licenses_lifecycle_claim" ON "fanmark_licenses" ("lifecycle_claim_id");
CREATE INDEX "fanmark_license_incarnations_scan" ON "fanmark_license_incarnations" ("license_id", "incarnation");
CREATE INDEX "license_expiry_run_items_cursor" ON "license_expiry_run_items" ("run_id", "license_id");
CREATE INDEX "fanmark_licenses_grace_finalization_scan" ON "fanmark_licenses" ("status", "grace_expires_at", "lifecycle_generation");
CREATE INDEX "license_grace_finalization_items_cursor" ON "license_grace_finalization_items" ("run_id", "license_id");
