-- STAGING ONLY: plan-bound business D1 runtime extension.
-- Generated by scripts/migration/business-schema-extensions.mjs.
-- DDL applies no Supabase or user rows; the final migration seeds one target runtime policy row.
-- Source fingerprint: 8435ff17c81ce4990da073b506465ea868a1e470af288fcc98c75621dae1b984
-- Extension digest: d46a7bf757dcbb70cb9833f3bb3f20216d4b26df034dfda8c96b8c99ff1126f3

CREATE TABLE "credential_transform_artifacts" (
  "artifact_id" TEXT PRIMARY KEY NOT NULL,
  "artifact_key" TEXT NOT NULL UNIQUE,
  "source_binding_digest" TEXT NOT NULL UNIQUE CHECK (length("source_binding_digest") = 64 AND "source_binding_digest" NOT GLOB '*[^0-9a-f]*'),
  "target_profile_fingerprint" TEXT NOT NULL CHECK (length("target_profile_fingerprint") = 64 AND "target_profile_fingerprint" NOT GLOB '*[^0-9a-f]*'),
  "source_manifest_digest" TEXT NOT NULL CHECK (length("source_manifest_digest") = 64 AND "source_manifest_digest" NOT GLOB '*[^0-9a-f]*'),
  "descriptor_digest" TEXT NOT NULL CHECK (length("descriptor_digest") = 64 AND "descriptor_digest" NOT GLOB '*[^0-9a-f]*'),
  "source_relation" TEXT NOT NULL CHECK ("source_relation" = 'fanmark_password_configs'),
  "source_primary_key_json" TEXT NOT NULL CHECK (length("source_primary_key_json") > 0),
  "source_row_identity_digest" TEXT NOT NULL CHECK (length("source_row_identity_digest") = 64 AND "source_row_identity_digest" NOT GLOB '*[^0-9a-f]*'),
  "source_envelope_digest" TEXT NOT NULL CHECK (length("source_envelope_digest") = 64 AND "source_envelope_digest" NOT GLOB '*[^0-9a-f]*'),
  "source_revision" TEXT NOT NULL CHECK (length("source_revision") > 0),
  "destination_relation" TEXT NOT NULL CHECK ("destination_relation" = 'fanmark_password_configs'),
  "destination_column" TEXT NOT NULL CHECK ("destination_column" = 'access_password'),
  "destination_license_id" TEXT NOT NULL CHECK (length("destination_license_id") > 0),
  "target_identity" TEXT NOT NULL CHECK (length("target_identity") > 0),
  "target_incarnation" TEXT NOT NULL CHECK (length("target_incarnation") > 0),
  "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
  "enabled" INTEGER NOT NULL CHECK ("enabled" IN (0, 1)),
  "codec_id" TEXT NOT NULL CHECK ("codec_id" = 'bcryptjs@3.0.3'),
  "codec_parameters_version" INTEGER NOT NULL CHECK (typeof("codec_parameters_version") = 'integer' AND "codec_parameters_version" BETWEEN 1 AND 9007199254740991),
  "codec_cost" INTEGER NOT NULL CHECK ("codec_cost" = 10),
  "transform_contract_version" INTEGER NOT NULL CHECK ("transform_contract_version" = 1),
  "policy_version" INTEGER NOT NULL CHECK ("policy_version" = 1),
  "expected_password_generation" INTEGER NOT NULL CHECK (typeof("expected_password_generation") = 'integer' AND "expected_password_generation" BETWEEN 0 AND 9007199254740991),
  "expected_access_generation" INTEGER NOT NULL CHECK (typeof("expected_access_generation") = 'integer' AND "expected_access_generation" BETWEEN 0 AND 9007199254740991),
  "expected_lifecycle_generation" INTEGER NOT NULL CHECK (typeof("expected_lifecycle_generation") = 'integer' AND "expected_lifecycle_generation" BETWEEN 0 AND 9007199254740991),
  "destination_hash" TEXT,
  "destination_transform_digest" TEXT UNIQUE CHECK ("destination_transform_digest" IS NULL OR length("destination_transform_digest") = 64 AND "destination_transform_digest" NOT GLOB '*[^0-9a-f]*'),
  "state" TEXT NOT NULL CHECK ("state" IN ('reserved', 'prepared', 'applied', 'reconciled', 'rejected')),
  "lease_id" TEXT,
  "lease_expires_at" INTEGER,
  "fencing_token" INTEGER NOT NULL CHECK (typeof("fencing_token") = 'integer' AND "fencing_token" BETWEEN 1 AND 9007199254740991),
  "created_at" TEXT NOT NULL,
  "prepared_at" TEXT,
  "applied_at" TEXT,
  "reconciled_at" TEXT,
  "failure_code" TEXT CHECK ("failure_code" IS NULL OR (length("failure_code") BETWEEN 1 AND 128 AND "failure_code" NOT GLOB '*[^a-z0-9_]*')),
  CHECK (("state" = 'reserved' AND "destination_hash" IS NULL AND "destination_transform_digest" IS NULL AND "prepared_at" IS NULL AND "applied_at" IS NULL AND "reconciled_at" IS NULL AND "failure_code" IS NULL)
      OR ("state" = 'prepared' AND "destination_hash" IS NOT NULL AND "destination_transform_digest" IS NOT NULL AND "prepared_at" IS NOT NULL AND "applied_at" IS NULL AND "reconciled_at" IS NULL AND "failure_code" IS NULL)
      OR ("state" = 'applied' AND "destination_hash" IS NOT NULL AND "destination_transform_digest" IS NOT NULL AND "prepared_at" IS NOT NULL AND "applied_at" IS NOT NULL AND "reconciled_at" IS NULL AND "failure_code" IS NULL)
      OR ("state" = 'reconciled' AND "destination_hash" IS NOT NULL AND "destination_transform_digest" IS NOT NULL AND "prepared_at" IS NOT NULL AND "applied_at" IS NOT NULL AND "reconciled_at" IS NOT NULL AND "failure_code" IS NULL)
      OR ("state" = 'rejected' AND "failure_code" IS NOT NULL))
);
CREATE TABLE "credential_transform_coverage" (
  "run_id" TEXT NOT NULL CHECK (length("run_id") > 0),
  "target_profile_fingerprint" TEXT NOT NULL CHECK (length("target_profile_fingerprint") = 64 AND "target_profile_fingerprint" NOT GLOB '*[^0-9a-f]*'),
  "source_manifest_digest" TEXT NOT NULL CHECK (length("source_manifest_digest") = 64 AND "source_manifest_digest" NOT GLOB '*[^0-9a-f]*'),
  "descriptor_digest" TEXT NOT NULL CHECK (length("descriptor_digest") = 64 AND "descriptor_digest" NOT GLOB '*[^0-9a-f]*'),
  "target_identity" TEXT NOT NULL CHECK (length("target_identity") > 0),
  "target_incarnation" TEXT NOT NULL CHECK (length("target_incarnation") > 0),
  "table_name" TEXT NOT NULL CHECK ("table_name" = 'fanmark_password_configs'),
  "source_primary_key_json" TEXT NOT NULL CHECK (length("source_primary_key_json") > 0),
  "source_row_identity_digest" TEXT NOT NULL CHECK (length("source_row_identity_digest") = 64 AND "source_row_identity_digest" NOT GLOB '*[^0-9a-f]*'),
  "source_envelope_digest" TEXT NOT NULL CHECK (length("source_envelope_digest") = 64 AND "source_envelope_digest" NOT GLOB '*[^0-9a-f]*'),
  "destination_relation" TEXT NOT NULL CHECK ("destination_relation" = 'fanmark_password_configs'),
  "destination_column" TEXT NOT NULL CHECK ("destination_column" = 'access_password'),
  "destination_primary_key_json" TEXT NOT NULL CHECK (length("destination_primary_key_json") > 0),
  "destination_license_id" TEXT NOT NULL CHECK (length("destination_license_id") > 0),
  "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
  "enabled" INTEGER NOT NULL CHECK ("enabled" IN (0, 1)),
  "expected_password_generation" INTEGER NOT NULL CHECK (typeof("expected_password_generation") = 'integer' AND "expected_password_generation" BETWEEN 0 AND 9007199254740991),
  "expected_access_generation" INTEGER NOT NULL CHECK (typeof("expected_access_generation") = 'integer' AND "expected_access_generation" BETWEEN 0 AND 9007199254740991),
  "expected_lifecycle_generation" INTEGER NOT NULL CHECK (typeof("expected_lifecycle_generation") = 'integer' AND "expected_lifecycle_generation" BETWEEN 0 AND 9007199254740991),
  "artifact_id" TEXT NOT NULL REFERENCES "credential_transform_artifacts"("artifact_id"),
  "fencing_token" INTEGER NOT NULL CHECK (typeof("fencing_token") = 'integer' AND "fencing_token" BETWEEN 1 AND 9007199254740991),
  "coverage_state" TEXT NOT NULL CHECK ("coverage_state" IN ('transformed', 'disabled', 'deferred_disabled', 'deferred_inactive', 'rejected')),
  "destination_transform_digest" TEXT CHECK ("destination_transform_digest" IS NULL OR length("destination_transform_digest") = 64 AND "destination_transform_digest" NOT GLOB '*[^0-9a-f]*'),
  "destination_digest" TEXT CHECK ("destination_digest" IS NULL OR length("destination_digest") = 64 AND "destination_digest" NOT GLOB '*[^0-9a-f]*'),
  "reason_code" TEXT CHECK ("reason_code" IS NULL OR (length("reason_code") BETWEEN 1 AND 128 AND "reason_code" NOT GLOB '*[^a-z0-9_]*')),
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY ("run_id", "table_name", "source_row_identity_digest"),
  UNIQUE ("target_identity", "target_incarnation", "table_name", "destination_primary_key_json"),
  UNIQUE ("target_identity", "target_incarnation", "destination_relation", "destination_column", "destination_license_id", "license_incarnation"),
  CHECK (("coverage_state" = 'transformed' AND "destination_transform_digest" IS NOT NULL AND "destination_digest" IS NOT NULL AND "reason_code" IS NULL)
      OR ("coverage_state" = 'disabled' AND "destination_transform_digest" IS NOT NULL AND "destination_digest" IS NOT NULL AND "reason_code" IS NULL)
      OR ("coverage_state" IN ('deferred_disabled', 'deferred_inactive', 'rejected') AND "destination_transform_digest" IS NULL AND "destination_digest" IS NULL AND "reason_code" IS NOT NULL))
);
CREATE INDEX "credential_transform_artifacts_target_state" ON "credential_transform_artifacts" ("target_identity", "target_incarnation", "state");
CREATE INDEX "credential_transform_artifacts_lease" ON "credential_transform_artifacts" ("state", "lease_expires_at");
CREATE INDEX "credential_transform_coverage_destination" ON "credential_transform_coverage" ("target_identity", "target_incarnation", "destination_license_id", "license_incarnation", "coverage_state");
CREATE INDEX "credential_transform_coverage_artifact" ON "credential_transform_coverage" ("artifact_id");
