-- STAGING ONLY: plan-bound business D1 runtime extension.
-- Generated by scripts/migration/business-schema-extensions.mjs.
-- DDL applies no Supabase or user rows; the final migration seeds one target runtime policy row.
-- Source fingerprint: 8435ff17c81ce4990da073b506465ea868a1e470af288fcc98c75621dae1b984
-- Extension digest: 817b2c1f6305dbbd0b3b09218c0abe57ad05ddbd3cce18160edadb9e8cb91ec7

CREATE TABLE "fanmark_password_runtime_evidence" (
      "license_id" TEXT PRIMARY KEY NOT NULL REFERENCES "fanmark_licenses"("id") ON DELETE CASCADE,
      "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
      "password_generation" INTEGER NOT NULL CHECK (typeof("password_generation") = 'integer' AND "password_generation" BETWEEN 0 AND 9007199254740991),
      "enabled" INTEGER NOT NULL CHECK ("enabled" IN (0, 1)),
      "codec_id" TEXT NOT NULL CHECK ("codec_id" = 'bcryptjs@3.0.3'),
      "created_at" TEXT NOT NULL,
      "updated_at" TEXT NOT NULL
    );
CREATE TABLE "fanmark_access_proofs" (
      "id" TEXT PRIMARY KEY NOT NULL,
      "token_hash" TEXT NOT NULL UNIQUE CHECK (length("token_hash") = 64 AND "token_hash" NOT GLOB '*[^0-9a-f]*'),
      "finalization_id" TEXT NOT NULL UNIQUE,
      "selector_kind" TEXT NOT NULL CHECK ("selector_kind" IN ('short', 'emoji', 'profile')),
      "selector_hash" TEXT NOT NULL CHECK (length("selector_hash") = 64 AND "selector_hash" NOT GLOB '*[^0-9a-f]*'),
      "fanmark_id" TEXT NOT NULL REFERENCES "fanmarks"("id") ON DELETE CASCADE,
      "license_id" TEXT NOT NULL REFERENCES "fanmark_licenses"("id") ON DELETE CASCADE,
      "password_generation" INTEGER NOT NULL CHECK (typeof("password_generation") = 'integer' AND "password_generation" BETWEEN 0 AND 9007199254740991),
      "access_generation" INTEGER NOT NULL CHECK (typeof("access_generation") = 'integer' AND "access_generation" BETWEEN 0 AND 9007199254740991),
      "license_incarnation" INTEGER NOT NULL CHECK (typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991),
      "created_at" TEXT NOT NULL,
      "expires_at" TEXT NOT NULL CHECK ("expires_at" > "created_at")
    );
CREATE TABLE "fanmark_access_rate_policy" (
      "id" INTEGER PRIMARY KEY CHECK ("id" = 1),
      "window_ms" INTEGER NOT NULL CHECK (typeof("window_ms") = 'integer' AND "window_ms" BETWEEN 1000 AND 9007199254740991),
      "max_attempts" INTEGER NOT NULL CHECK (typeof("max_attempts") = 'integer' AND "max_attempts" BETWEEN 1 AND 9007199254740991),
      "reservation_ms" INTEGER NOT NULL CHECK (typeof("reservation_ms") = 'integer' AND "reservation_ms" BETWEEN 1 AND 9007199254740991 AND "reservation_ms" <= "window_ms")
    );
CREATE TABLE "fanmark_access_rate_limits" (
      "bucket_kind" TEXT NOT NULL CHECK ("bucket_kind" IN ('requester', 'resource')),
      "bucket_hash" TEXT NOT NULL CHECK (length("bucket_hash") = 64 AND "bucket_hash" NOT GLOB '*[^0-9a-f]*'),
      "window_id" INTEGER NOT NULL CHECK (typeof("window_id") = 'integer' AND "window_id" BETWEEN 0 AND 9007199254740991),
      "window_started_at" INTEGER NOT NULL CHECK (typeof("window_started_at") = 'integer' AND "window_started_at" BETWEEN 0 AND 9007199254740991),
      "window_expires_at" INTEGER NOT NULL CHECK (typeof("window_expires_at") = 'integer' AND "window_expires_at" BETWEEN 0 AND 9007199254740991 AND "window_expires_at" > "window_started_at"),
      "attempt_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("attempt_count") = 'integer' AND "attempt_count" BETWEEN 0 AND 9007199254740991),
      "failure_count" INTEGER NOT NULL DEFAULT 0 CHECK (typeof("failure_count") = 'integer' AND "failure_count" BETWEEN 0 AND 9007199254740991),
      "cooldown_until" INTEGER CHECK ("cooldown_until" IS NULL OR typeof("cooldown_until") = 'integer' AND "cooldown_until" BETWEEN 0 AND 9007199254740991),
      "updated_at" INTEGER NOT NULL CHECK (typeof("updated_at") = 'integer' AND "updated_at" BETWEEN 0 AND 9007199254740991),
      PRIMARY KEY ("bucket_kind", "bucket_hash")
    );
CREATE TABLE "fanmark_access_attempt_reservations" (
      "reservation_id" TEXT PRIMARY KEY NOT NULL,
      "requester_bucket_hash" TEXT NOT NULL CHECK (length("requester_bucket_hash") = 64 AND "requester_bucket_hash" NOT GLOB '*[^0-9a-f]*'),
      "resource_bucket_hash" TEXT NOT NULL CHECK (length("resource_bucket_hash") = 64 AND "resource_bucket_hash" NOT GLOB '*[^0-9a-f]*'),
      "license_id" TEXT REFERENCES "fanmark_licenses"("id") ON DELETE SET NULL,
      "selector_hash" TEXT NOT NULL CHECK (length("selector_hash") = 64 AND "selector_hash" NOT GLOB '*[^0-9a-f]*'),
      "window_id" INTEGER NOT NULL CHECK (typeof("window_id") = 'integer' AND "window_id" BETWEEN 0 AND 9007199254740991),
      "reserved_at" INTEGER NOT NULL CHECK (typeof("reserved_at") = 'integer' AND "reserved_at" BETWEEN 0 AND 9007199254740991),
      "reservation_expires_at" INTEGER NOT NULL CHECK (typeof("reservation_expires_at") = 'integer' AND "reservation_expires_at" BETWEEN 0 AND 9007199254740991),
      "outcome" TEXT NOT NULL CHECK ("outcome" IN ('reserved', 'success', 'failure', 'expired', 'stale')),
      "finalization_id" TEXT UNIQUE,
      "completed_at" INTEGER CHECK ("completed_at" IS NULL OR typeof("completed_at") = 'integer' AND "completed_at" BETWEEN 0 AND 9007199254740991),
      CHECK ("outcome" <> 'reserved' OR ("finalization_id" IS NULL AND "completed_at" IS NULL)),
      CHECK ("outcome" = 'reserved' OR ("finalization_id" IS NOT NULL AND "completed_at" IS NOT NULL))
    );
CREATE TABLE "fanmark_access_attempt_audit" (
      "id" TEXT PRIMARY KEY NOT NULL,
      "reservation_id" TEXT NOT NULL,
      "license_id" TEXT REFERENCES "fanmark_licenses"("id") ON DELETE SET NULL,
      "selector_hash" TEXT CHECK ("selector_hash" IS NULL OR length("selector_hash") = 64 AND "selector_hash" NOT GLOB '*[^0-9a-f]*'),
      "requester_hash" TEXT NOT NULL CHECK (length("requester_hash") = 64 AND "requester_hash" NOT GLOB '*[^0-9a-f]*'),
      "outcome" TEXT NOT NULL CHECK ("outcome" IN ('blocked', 'failure', 'expired', 'success', 'stale')),
      "occurred_at" INTEGER NOT NULL CHECK (typeof("occurred_at") = 'integer' AND "occurred_at" BETWEEN 0 AND 9007199254740991),
      "password_generation" INTEGER CHECK ("password_generation" IS NULL OR typeof("password_generation") = 'integer' AND "password_generation" BETWEEN 0 AND 9007199254740991),
      "access_generation" INTEGER CHECK ("access_generation" IS NULL OR typeof("access_generation") = 'integer' AND "access_generation" BETWEEN 0 AND 9007199254740991),
      "license_incarnation" INTEGER CHECK ("license_incarnation" IS NULL OR typeof("license_incarnation") = 'integer' AND "license_incarnation" BETWEEN 0 AND 9007199254740991)
    );
CREATE INDEX "fanmark_access_proofs_lookup_idx" ON "fanmark_access_proofs" ("token_hash", "selector_kind", "selector_hash");
CREATE INDEX "fanmark_access_proofs_expiry_idx" ON "fanmark_access_proofs" ("license_id", "expires_at");
CREATE INDEX "fanmark_access_rate_limits_window_idx" ON "fanmark_access_rate_limits" ("window_expires_at");
CREATE INDEX "fanmark_access_attempt_reservations_expiry_idx" ON "fanmark_access_attempt_reservations" ("outcome", "reservation_expires_at");
CREATE INDEX "fanmark_access_attempt_audit_license_idx" ON "fanmark_access_attempt_audit" ("license_id", "occurred_at");
CREATE TRIGGER "verified_access_reservation_guard"
      BEFORE INSERT ON "fanmark_access_attempt_reservations"
      WHEN new."outcome" = 'reserved'
      BEGIN
        SELECT RAISE(ABORT, 'reservation blocked')
        WHERE NOT EXISTS (
          SELECT 1 FROM "fanmark_access_rate_limits"
          WHERE "bucket_kind" = 'requester' AND "bucket_hash" = new."requester_bucket_hash"
            AND "window_id" = new."window_id"
            AND "attempt_count" < (SELECT "max_attempts" FROM "fanmark_access_rate_policy" WHERE "id" = 1)
            AND ("cooldown_until" IS NULL OR "cooldown_until" <= new."reserved_at")
        ) OR NOT EXISTS (
          SELECT 1 FROM "fanmark_access_rate_limits"
          WHERE "bucket_kind" = 'resource' AND "bucket_hash" = new."resource_bucket_hash"
            AND "window_id" = new."window_id"
            AND "attempt_count" < (SELECT "max_attempts" FROM "fanmark_access_rate_policy" WHERE "id" = 1)
            AND ("cooldown_until" IS NULL OR "cooldown_until" <= new."reserved_at")
        ) OR new."reservation_expires_at" <= new."reserved_at";
      END;
CREATE TRIGGER "verified_access_reservation_increment"
      AFTER INSERT ON "fanmark_access_attempt_reservations"
      WHEN new."outcome" = 'reserved'
      BEGIN
        UPDATE "fanmark_access_rate_limits"
        SET "attempt_count" = "attempt_count" + 1, "updated_at" = new."reserved_at"
        WHERE "window_id" = new."window_id"
          AND (("bucket_kind" = 'requester' AND "bucket_hash" = new."requester_bucket_hash")
            OR ("bucket_kind" = 'resource' AND "bucket_hash" = new."resource_bucket_hash"));
      END;
CREATE TRIGGER "verified_access_reservation_success_guard"
      BEFORE UPDATE OF "outcome" ON "fanmark_access_attempt_reservations"
      WHEN old."outcome" = 'reserved' AND new."outcome" = 'success'
        AND (new."completed_at" IS NULL OR new."completed_at" >= old."reservation_expires_at")
      BEGIN
        SELECT RAISE(ABORT, 'reservation expired');
      END;
CREATE TRIGGER "verified_access_reservation_failure_increment"
      AFTER UPDATE OF "outcome" ON "fanmark_access_attempt_reservations"
      WHEN old."outcome" = 'reserved' AND new."outcome" = 'failure'
      BEGIN
        UPDATE "fanmark_access_rate_limits"
        SET "failure_count" = "failure_count" + 1,
            "cooldown_until" = MAX(COALESCE("cooldown_until", 0),
              CASE WHEN "failure_count" + 1 >= (SELECT "max_attempts" FROM "fanmark_access_rate_policy" WHERE "id" = 1)
                THEN new."completed_at" + 60000 ELSE COALESCE("cooldown_until", 0) END),
            "updated_at" = new."completed_at"
        WHERE "window_id" = old."window_id"
          AND (("bucket_kind" = 'requester' AND "bucket_hash" = old."requester_bucket_hash")
            OR ("bucket_kind" = 'resource' AND "bucket_hash" = old."resource_bucket_hash"));
      END;
INSERT INTO "fanmark_access_rate_policy" ("id", "window_ms", "max_attempts", "reservation_ms") VALUES (1, 300000, 5, 30000) ON CONFLICT("id") DO NOTHING;
