import { promises as fs } from "fs";
import path from "path";
import { pathToFileURL } from "node:url";
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../src/integrations/supabase/types";

const INPUT_PATH = path.resolve("data/emoji/emoji-master.json");
const OUTPUT_PATH = path.resolve("src/data/emojiCatalog.ts");

export interface EmojiMasterRecord {
  id: string;
  emoji: string;
  short_name: string;
  keywords: string[];
  category: string | null;
  subcategory: string | null;
  codepoints: string[];
  sort_order: number | null;
}

interface EmojiCatalogEntry {
  id: string;
  emoji: string;
  shortName: string;
  keywords: string[];
  category: string | null;
  subcategory: string | null;
  codepoints: string[];
}

interface EmojiCatalog {
  entries: EmojiCatalogEntry[];
  idToEmoji: Record<string, string>;
  emojiToId: Record<string, string>;
  categories: Record<string, string[]>;
}

const FE_VARIATION_SELECTOR_REGEX = /\uFE0F+/g;

const normalizeEmojiForLookup = (emoji: string): string =>
  emoji.normalize("NFC").replace(FE_VARIATION_SELECTOR_REGEX, "\uFE0F");

export const generateCatalog = (records: EmojiMasterRecord[]): EmojiCatalog => {
  validateRecords(records);
  const sorted = [...records].sort((a, b) => {
    const aOrder = a.sort_order ?? Number.MAX_SAFE_INTEGER;
    const bOrder = b.sort_order ?? Number.MAX_SAFE_INTEGER;
    if (aOrder !== bOrder) {
      return aOrder - bOrder;
    }
    return a.emoji.localeCompare(b.emoji);
  });

  const entries: EmojiCatalogEntry[] = sorted.map((record) => ({
    id: record.id,
    emoji: record.emoji,
    shortName: record.short_name,
    keywords: record.keywords,
    category: record.category,
    subcategory: record.subcategory,
    codepoints: record.codepoints,
  }));

  const idToEmoji: Record<string, string> = {};
  const emojiToId: Record<string, string> = {};
  const categories: Record<string, string[]> = {};

  entries.forEach((entry) => {
    idToEmoji[entry.id] = entry.emoji;
    emojiToId[normalizeEmojiForLookup(entry.emoji)] = entry.id;

    if (entry.category) {
      const categoryKey = entry.category;
      if (!categories[categoryKey]) {
        categories[categoryKey] = [];
      }
      categories[categoryKey].push(entry.id);
    }
  });

  Object.values(categories).forEach((list) => {
    list.sort((a, b) => {
      const entryA = idToEmoji[a];
      const entryB = idToEmoji[b];
      return normalizeEmojiForLookup(entryA).localeCompare(normalizeEmojiForLookup(entryB));
    });
  });

  return {
    entries,
    idToEmoji,
    emojiToId,
    categories,
  };
};

export const generateModuleSource = (catalog: EmojiCatalog): string => {
  const header = `// Auto-generated by scripts/generate-emoji-catalog.ts\n// Do not edit this file directly.\n\n`;

  const entriesSource = `export const emojiCatalogEntries = ${JSON.stringify(catalog.entries, null, 2)} as const;\n`;
  const idToEmojiSource = `export const emojiIdToEmoji: Record<string, string> = ${JSON.stringify(catalog.idToEmoji, null, 2)};\n`;
  const emojiToIdSource = `export const emojiToId: Record<string, string> = ${JSON.stringify(catalog.emojiToId, null, 2)};\n`;
  const categoriesSource = `export const emojiCategories: Record<string, string[]> = ${JSON.stringify(catalog.categories, null, 2)};\n`;

  const defaultExport = `\nexport default {\n  entries: emojiCatalogEntries,\n  idToEmoji: emojiIdToEmoji,\n  emojiToId,\n  categories: emojiCategories,\n};\n`;

  return header + entriesSource + idToEmojiSource + emojiToIdSource + categoriesSource + defaultExport;
};

export function validateRecords(records: unknown): asserts records is EmojiMasterRecord[] {
  if (!Array.isArray(records) || records.length === 0) throw new Error("Expected a nonempty UUID-bearing emoji record array");
  const ids = new Set<string>();
  const emojis = new Set<string>();
  for (const record of records) {
    if (!record || typeof record !== "object" ||
        typeof record.id !== "string" || !/^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i.test(record.id) ||
        typeof record.emoji !== "string" || record.emoji.length === 0 ||
        typeof record.short_name !== "string" ||
        !Array.isArray(record.keywords) || !record.keywords.every((x: unknown) => typeof x === "string") ||
        !Array.isArray(record.codepoints) || record.codepoints.length === 0 ||
        !record.codepoints.every((x: unknown) => typeof x === "string" && /^[0-9A-F]{4,6}$/.test(x)) ||
        !(record.category === null || typeof record.category === "string") ||
        !(record.subcategory === null || typeof record.subcategory === "string") ||
        !(record.sort_order === null || Number.isSafeInteger(record.sort_order))) {
      throw new Error("Invalid emoji catalog record; export the database UUIDs and required columns");
    }
    const normalized = normalizeEmojiForLookup(record.emoji);
    if (ids.has(record.id.toLowerCase()) || emojis.has(normalized)) {
      throw new Error("Duplicate UUID or ambiguous normalized emoji in catalog input");
    }
    ids.add(record.id.toLowerCase());
    emojis.add(normalized);
  }
}

export function parseArguments(argv: string[]) {
  let input: string | undefined;
  let output = OUTPUT_PATH;
  let outputSeen = false;
  for (let i = 0; i < argv.length; i++) {
    const option = argv[i];
    const value = argv[++i];
    if (!value || value.startsWith("--")) throw new Error("Expected a path after --input or --output");
    if (option === "--input" && input === undefined) input = path.resolve(value);
    else if (option === "--output" && !outputSeen) { output = path.resolve(value); outputSeen = true; }
    else throw new Error("Unknown or repeated catalog option");
  }
  if (input === output) throw new Error("Input and output paths must differ");
  return { input, output };
}

export const main = async (argv = process.argv.slice(2)) => {
  const { input, output } = parseArguments(argv);

  let records: EmojiMasterRecord[];

  const supabaseUrl = process.env.SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!input && supabaseUrl && serviceRoleKey) {
    const supabase = createClient<Database>(supabaseUrl, serviceRoleKey);

    const pageSize = 1000;
    let from = 0;
    let finished = false;
    const aggregated: EmojiMasterRecord[] = [];

    while (!finished) {
      const to = from + pageSize - 1;
      const { data, error } = await supabase
        .from("emoji_master")
        .select("id, emoji, short_name, keywords, category, subcategory, codepoints, sort_order")
        .order("sort_order", { ascending: true, nullsFirst: true })
        .order("emoji", { ascending: true })
        .range(from, to);

      if (error) {
        throw new Error(`Failed to fetch emoji_master from Supabase: ${error.message}`);
      }

      const batch = (data ?? []) as EmojiMasterRecord[];
      aggregated.push(...batch);

      if (batch.length < pageSize) {
        finished = true;
      } else {
        from += pageSize;
      }
    }

    records = aggregated;
  } else {
    const jsonRaw = await fs.readFile(input ?? INPUT_PATH, "utf-8");
    const parsed: unknown = JSON.parse(jsonRaw);
    validateRecords(parsed);
    records = parsed;
  }

  const catalog = generateCatalog(records);
  const moduleSource = generateModuleSource(catalog);

  await fs.mkdir(path.dirname(output), { recursive: true });
  const temporary = `${output}.${randomUUID()}.tmp`;
  try {
    await fs.writeFile(temporary, moduleSource, { encoding: "utf-8", flag: "wx" });
    await fs.rename(temporary, output);
  } finally {
    await fs.rm(temporary, { force: true });
  }

  console.log(`Emoji catalog generated: ${path.relative(process.cwd(), output)}`);
  console.log(`Entries: ${catalog.entries.length}`);
};

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) main().catch((error) => {
  console.error("Failed to generate emoji catalog:", error);
  process.exit(1);
});
