import { promises as fs } from "fs";
import path from "path";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../src/integrations/supabase/types";

const INPUT_PATH = path.resolve("data/emoji/emoji-master.json");
const OUTPUT_PATH = path.resolve("src/data/emojiCatalog.ts");

interface EmojiMasterRecord {
  id: string;
  emoji: string;
  short_name: string;
  keywords: string[];
  category: string | null;
  subcategory: string | null;
  codepoints: string[];
  sort_order: number | null;
}

interface EmojiCatalogEntry {
  id: string;
  emoji: string;
  shortName: string;
  keywords: string[];
  category: string | null;
  subcategory: string | null;
  codepoints: string[];
}

interface EmojiCatalog {
  entries: EmojiCatalogEntry[];
  idToEmoji: Record<string, string>;
  emojiToId: Record<string, string>;
  categories: Record<string, string[]>;
}

const FE_VARIATION_SELECTOR_REGEX = /\uFE0F+/g;

const normalizeEmojiForLookup = (emoji: string): string =>
  emoji.normalize("NFC").replace(FE_VARIATION_SELECTOR_REGEX, "\uFE0F");

const generateCatalog = (records: EmojiMasterRecord[]): EmojiCatalog => {
  const sorted = [...records].sort((a, b) => {
    const aOrder = a.sort_order ?? Number.MAX_SAFE_INTEGER;
    const bOrder = b.sort_order ?? Number.MAX_SAFE_INTEGER;
    if (aOrder !== bOrder) {
      return aOrder - bOrder;
    }
    return a.emoji.localeCompare(b.emoji);
  });

  const entries: EmojiCatalogEntry[] = sorted.map((record) => ({
    id: record.id,
    emoji: record.emoji,
    shortName: record.short_name,
    keywords: record.keywords,
    category: record.category,
    subcategory: record.subcategory,
    codepoints: record.codepoints,
  }));

  const idToEmoji: Record<string, string> = {};
  const emojiToId: Record<string, string> = {};
  const categories: Record<string, string[]> = {};

  entries.forEach((entry) => {
    idToEmoji[entry.id] = entry.emoji;
    emojiToId[normalizeEmojiForLookup(entry.emoji)] = entry.id;

    if (entry.category) {
      const categoryKey = entry.category;
      if (!categories[categoryKey]) {
        categories[categoryKey] = [];
      }
      categories[categoryKey].push(entry.id);
    }
  });

  Object.values(categories).forEach((list) => {
    list.sort((a, b) => {
      const entryA = idToEmoji[a];
      const entryB = idToEmoji[b];
      return normalizeEmojiForLookup(entryA).localeCompare(normalizeEmojiForLookup(entryB));
    });
  });

  return {
    entries,
    idToEmoji,
    emojiToId,
    categories,
  };
};

const generateModuleSource = (catalog: EmojiCatalog): string => {
  const header = `// Auto-generated by scripts/generate-emoji-catalog.ts\n// Do not edit this file directly.\n\n`;

  const entriesSource = `export const emojiCatalogEntries = ${JSON.stringify(catalog.entries, null, 2)} as const;\n`;
  const idToEmojiSource = `export const emojiIdToEmoji: Record<string, string> = ${JSON.stringify(catalog.idToEmoji, null, 2)};\n`;
  const emojiToIdSource = `export const emojiToId: Record<string, string> = ${JSON.stringify(catalog.emojiToId, null, 2)};\n`;
  const categoriesSource = `export const emojiCategories: Record<string, string[]> = ${JSON.stringify(catalog.categories, null, 2)};\n`;

  const defaultExport = `\nexport default {\n  entries: emojiCatalogEntries,\n  idToEmoji: emojiIdToEmoji,\n  emojiToId,\n  categories: emojiCategories,\n};\n`;

  return header + entriesSource + idToEmojiSource + emojiToIdSource + categoriesSource + defaultExport;
};

const main = async () => {
  let records: EmojiMasterRecord[];

  const supabaseUrl = process.env.SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (supabaseUrl && serviceRoleKey) {
    const supabase = createClient<Database>(supabaseUrl, serviceRoleKey);

    const pageSize = 1000;
    let from = 0;
    let finished = false;
    const aggregated: EmojiMasterRecord[] = [];

    while (!finished) {
      const to = from + pageSize - 1;
      const { data, error } = await supabase
        .from("emoji_master")
        .select("id, emoji, short_name, keywords, category, subcategory, codepoints, sort_order")
        .order("sort_order", { ascending: true, nullsFirst: true })
        .order("emoji", { ascending: true })
        .range(from, to);

      if (error) {
        throw new Error(`Failed to fetch emoji_master from Supabase: ${error.message}`);
      }

      const batch = (data ?? []) as EmojiMasterRecord[];
      aggregated.push(...batch);

      if (batch.length < pageSize) {
        finished = true;
      } else {
        from += pageSize;
      }
    }

    records = aggregated;
  } else {
    const jsonRaw = await fs.readFile(INPUT_PATH, "utf-8");
    const parsed = JSON.parse(jsonRaw) as Partial<EmojiMasterRecord>[];

    const missingId = parsed.some((record) => !record.id);
    if (missingId) {
      throw new Error(
        "emoji-master.json には id が含まれていません。SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY を設定して Supabase から取得してください。",
      );
    }

    records = parsed as EmojiMasterRecord[];
  }

  const catalog = generateCatalog(records);
  const moduleSource = generateModuleSource(catalog);

  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, moduleSource, "utf-8");

  console.log(`Emoji catalog generated: ${path.relative(process.cwd(), OUTPUT_PATH)}`);
  console.log(`Entries: ${catalog.entries.length}`);
};

main().catch((error) => {
  console.error("Failed to generate emoji catalog:", error);
  process.exit(1);
});
